name: Repository Database Maintenance

on:
  schedule:
    # 2 haftada bir Pazar gecesi 00:00
    - cron: '0 0 */14 * *'
  workflow_dispatch: # Manuel çalıştırma imkanı

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install httpx

      - name: Run Status Check and Auto-Remove
        env:
          GITHUB_TOKEN: ${{ secrets.SCAN_TOKEN }}
        run: |
          
          echo y | python check_repos_status.py

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add detected_repos.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: cleanup deleted repositories from database" && git push)
